### ISSUE TITLE
WebhoseQuery's siteTypes parameter is not working

### ISSUE THREAD

**Issue by stanleywym** [Buzzilla/webhose-java#1]
WebhoseQuery's siteTypes parameter is not working. If the siteTypes parameter is set, no result will be returned. It's due to toString() method in com.buzzilla.webhose.client.WebhoseQuery is passing the wrong field name. The field name should be "site_type" instead of "siteType".

**Comment by IdanHaim** [comment]
Thank you. i fixed all the WebhoseQuery today so you can download it and tell me if there are any more problems.

**Comment by stanleywym** [comment]
Thank @IdanHaim. I just noticed this has been fixed in version 0.1.1 and I was using version 0.1.0 previously. It would help if the installation section in README.md is updated to use 0.1.1 instead of 0.1.0.

**Comment by itsadok** [comment]
Fixed README in 09a9dd3. Thanks @stanleywym.
