### ISSUE TITLE
How to set timestamp query parameter

### ISSUE THREAD

**Issue by Hronom** [Buzzilla/webhose-java#2]
How to set the `ts` parameter https://webhose.io/documentation ?

**Comment by rangeva** [comment]
We have added another search function when you can specify the ts timestamp parameter:

https://github.com/Buzzilla/webhose-java/blob/master/src/main/java/com/buzzilla/webhose/client/WebhoseClient.java

**Comment by Hronom** [comment]
Thanks, wait this in maven central
