### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by EXJUSTICE** [Buzzilla/webhose-java#8]
Hello,

I have been using you're API without issue for about a month. However it has suddenly stopped responding, with no queries shown on my dashboard either.

Is the API down?

**Comment by rangeva** [comment]
Hi, it might be an https issues, try replacing https with http on the endpoint:
I've already updated the following file:
https://github.com/Buzzilla/webhose-java/blob/master/src/main/java/com/buzzilla/webhose/client/WebhoseClient.java

**Comment by EXJUSTICE** [comment]
Can you release an update on maven? I'm locked from editing your API on studio.

**Comment by EXJUSTICE** [comment]
The code you've changed still had one https. removed it, and it started working.

Two methods now look like this

`public WebhoseResponse search(String query, Long ts) throws IOException {
        WebhoseUrl url = new WebhoseUrl("http://webhose.io/search");
        url.token = this.apiKey;
        url.query = query;
        url.fromTimestamp = ts;

        HttpRequest request = requestFactory.buildGetRequest(url);
        return request.execute().parseAs(WebhoseResponse.class);
    }

    public WebhoseResponse getMore(WebhoseResponse response) throws IOException {
        WebhoseUrl url = new WebhoseUrl("http://webhose.io" + response.next);

        HttpRequest request = requestFactory.buildGetRequest(url);

        return request.execute().parseAs(WebhoseResponse.class);
    }`
